name: Build and Publish a Maven package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Find main JAR artifact
      id: find-jar
      run: |
        jar_path=$(find target -name 'VerifyDiscordMembers-*.jar' ! -name '*-plugin.jar')
        echo "jar=$jar_path" >> $GITHUB_ENV

    - name: Upload JAR artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: verify-discord-members-jar
        path: ${{ env.jar }}

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download JAR artifact
      uses: actions/download-artifact@v3
      with:
        name: verify-discord-members-jar
        path: ./downloaded-artifact
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./downloaded-artifact/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
